/*
 Navicat Premium Data Transfer

 Source Server         : zhong
 Source Server Type    : MySQL
 Source Server Version : 80023
 Source Host           : localhost:3306
 Source Schema         : localnote

 Target Server Type    : MySQL
 Target Server Version : 80023
 File Encoding         : 65001

 Date: 15/04/2021 22:24:23
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for note
-- ----------------------------
DROP TABLE IF EXISTS `note`;
CREATE TABLE `note`  (
  `note_id` int(0) NOT NULL AUTO_INCREMENT,
  `note_title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `note_content` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `note_limit` int(0) NOT NULL,
  `note_date` date NULL DEFAULT NULL,
  `user_id` int(0) NOT NULL,
  PRIMARY KEY (`note_id`) USING BTREE,
  INDEX `user_id`(`user_id`) USING BTREE,
  CONSTRAINT `user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 16 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of note
-- ----------------------------
INSERT INTO `note` VALUES (3, '青铜鬼棺（1）', '第一章 血染老虎岭\r\n\r\n梦，好长的一个梦，我在仿佛这场幻境中挣扎了几千年，梦将醒时，这千载的记忆好似被什么东西镇压住了一般，永远的风存在脑海深处的某个地方，让我无法探寻，留给我的记忆中，只有一片殷红的混沌。\r\n\r\n耳边的嘈杂声吵醒了我，我的意识逐渐清晰，我感到身子下一阵冰凉，这感觉好熟悉，真的好熟悉，忽然，一段前世的回忆在脑海里唤醒，这里难道是?地下第八层的……\r\n\r\n冰山地狱!恐惧袭来，我猛的睁开眼坐起，左手条件反射的抓向腰间的桃木剑，此时，围在我周边看热闹的人群一阵惊呼，慌忙向后退去，我看着他们突然放大的瞳孔中，流露着恐惧，便索性不去搭理他们。\r\n\r\n我观察着四周，我所在的地方是一座校园，周围绿树成荫，空气中弥漫着桂花的香气，又抬头望去，不远处的一座高楼上挂着用LED灯点亮的六个吸塑字——“湖南美术学院”。\r\n\r\n这里是……人间!我怎么会在这里?我前世的记忆已经成了碎片，只记得我的名字叫司少泽，是美院大一的学生，在学习油画，资质平平，不受导师赏识，其余的，唉…算了!越想越头痛。\r\n\r\n我伸出手，想支起身体爬起来，可右臂一阵麻木，我身子一软，又倒在了地上，四周围观的人群一阵嬉笑声“这小子喝多了吧。”“哈哈哈，别去扶他，看他能不能起来。”“走吧，别看了，可能是碰瓷的，别被赖上惹一身骚。”\r\n\r\n当我再次倒在地上时，我透过人群的缝隙，看到的不远处的一张牌子，上面写着——楚枫桥，啊!怎么是这里?想起来了，我的前世是地狱八层镇狱军的一名裨将，因为酒后贻误军机，丢失了抢夺青铜鬼棺的良机，被伏波将军贬为校尉。\r\n\r\n那青铜鬼棺是战国时期的阴阳师鬼谷子所炼制，镇压着鬼王伯奇，当年鬼王出世，掀起了一场腥风血雨，各诸侯国间受鬼王的操控，相互残杀，死了千百万无辜的黎民，最终在茅山和崂山道士的帮助下，鬼谷子用自己的心脏里的精血祭天，镇压住了鬼王伯奇。\r\n\r\n可过了几千年，天道不稳，鬼王伯奇的实力不断提升， 一股精神力召唤出了地狱的鬼物，帮助自己举行复活仪式，幸好阴谋被镇狱军发现，对鬼物展开了绞杀，最终鬼物们带着青铜鬼棺退守到了老虎岭。\r\n\r\n由于我善于指挥奇袭，手中还有家族传下的八卦镇尸镜，伏波将军让我在老虎岭战役中担任前锋，可没想到，这正中了地狱里逃出的那些鬼物圈套，他们最忌惮的法器在我手中，自然要想方设法的害我，没想到，伏波将军真的上了他们的当。\r\n\r\n一行五百名军士连夜行军来到了老虎岭下的楚枫桥，此桥乃是通往老虎岭的必经之路，只有夺下这里，才能保证大军顺利通行，此时已经是子时，地狱中阴气最重的时候，鬼物们隐藏在楚枫桥下，之前派出的两队斥候已经被他们吸干了脑髓。\r\n\r\n“将军!不能再进了，前方大雾弥山，必有埋伏，”手下的军校说 “不如我们先布下阵法，就地扎营，等待大军到时一同进攻。”\r\n\r\n“我现在是先锋校尉，哪里轮到你指挥?”我冷冷的看着他，目光交汇，那军校慌忙底下头去 “属下该死，不敢违抗将军。”\r\n\r\n此时一阵阴风袭来，温度的骤然降了下来，心头微微一震，哼，雕虫小技，我将配剑重重插到地上，转过身向镇狱军说 “所有人马分成两队，前队冲锋，后队督战，若前队有退过此剑者，后队斩前队。”我用手中的青龙戟指向老虎岭说 “妖物就在此岭，伯奇逃离地狱，祸乱人间，我现在已经是前队的士兵了，大家随我冲!”\r\n\r\n一时间杀声震天，几百名镇狱军争先恐后的冲向楚枫桥。可就当桥渡了一半，忽然无数的鬼影从桥下飘起，楚枫桥一阵狂颤，带头的是一只魍魉，他一袭白衣，手持绫绢扇，“将军，好久不见啊。”\r\n\r\n我大惊“是你?”“没错，正是本座，你在血池地狱困了我三百年，没想到我们还能在这里见面，可真是天要亡你呀，哈哈哈……”\r\n\r\n遭了，中计了，我手下的镇狱军都没有佩戴镇邪祟符，这魍魉最喜欢蚕食人的欲望，如果没有符的保护，他们会全部被控制，到时候就是全军覆没。\r\n\r\n我不敢多耽搁，直接拿出八卦镇尸镜，随着口中一连串的咒语，八卦镜飞向天空，照向那数不尽的鬼物，可是为时已晚，前锋军已有半数以上的军士被魍魉控制，开始和自己的战友相互残杀。\r\n\r\n这场仗打得天昏地暗，最终我还是凭借着八卦镇尸镜，打伤了那只魍魉，鬼物见情况不妙，慌忙褪去。\r\n\r\n我扶在桥头喘着粗气，喝住了几个想去追敌已经杀得眼红的士兵，此时，身后响起了士兵们的欢呼声“胜利胜利!胜利胜利!胜利胜利……”我终于松了一口气，此仗是老虎岭战役的首胜，现在消息应该已经传到了中军大营，我也算是没辜负伏波将军。\r\n\r\n“将军，我们终于赢了。”我肩膀上忽然多了一只手，我侧过身看去，是那个之前反对我的军校，我说 “你们辛苦了，这次赢得艰难，我们回去要好好安抚阵亡将士的亲人。”\r\n\r\n“我的二哥刚战死了，我现在就是阵亡将士的亲属。”突然他眼中闪过一丝鬼气 “我要让你偿命!”当我意识到他的心智已经被魍魉控制住时，为时已晚。\r\n\r\n一把钢刀迎着我的面门劈下，我一个闪身，可因为离得太近，没有心理准备，我的右臂被生生劈断，几个手下看到，用盾牌奋力抵挡，将那军校击退。\r\n\r\n我捂着右臂还在喷血伤口，“噗通”一声倒下，昏了过去……', 1, '2021-04-09', 1);
INSERT INTO `note` VALUES (4, '青铜鬼棺（2）', '第二章 偶遇故人\r\n\r\n我从回忆中惊醒，慌忙起身，此时巡逻的保安已经走了过来“同学，你没事吧，是不是生病了，要不要送你去医院?”\r\n\r\n“不必了，我没事，昨晚出去蹦迪多喝了点酒。”我也不等保安细问，紧忙挤出人群，顺着前世的记忆向寝室方向走去。\r\n\r\n一推开门，几个室友都忙着打王者，随口招呼了一声，就继续“战斗”，我拖着疲惫的身躯扑向我的床铺，顺手抓向床头的几个烟盒子，心想这小子还挺会生活呀，只不过现在他的记忆被我覆盖了，那我就替他享受一下吧。\r\n\r\n点燃了一支芙蓉王，深吸一口，倚着墙瘫了下去，不禁感叹，这可比嘉庆时的旱烟斗子好多了，这过了么些年，世界变化可真大啊。\r\n\r\n在前世我就是个闲不下的人，伏波将军没给我作战任务的时候，我就在地狱里到处闯荡，其实说白了就是去挑事打架，反正地狱里都不是什么好鸟，随便收拾几个也就当为民除害了，所以我当年在地狱里一番折腾之后，鬼王修为以下的妖物见了我都是闻风丧胆。\r\n\r\n在寝室睡了几天，我感觉修为都快减退了，前世师傅总是教导我们要勤修苦练，时不时就带着我和几个师兄们出去历练，当时的我好吃懒做，总想着把累活塞给师兄们，每次被师傅发现时，都会罚我扎马步、顶大缸，我口里不说，心里却满是怨言，后来全都化作捉弄师兄的动力了，现在回忆起来，那段日子才是最幸福的。\r\n\r\n这天我被迫上了一整天的课，装模作样的画了一天苹果梨后，迷迷糊糊的爬出画室，向食堂的方向走去，忽然我眼前一亮，一个穿着卡其色风衣的少年迎面走来，手里抱着画板，急匆匆的赶路，走近时我发现他颈窝上有一块刀疤型的胎记，只有前世在战场混过的人，才会有那样的疤痕。\r\n\r\n我去~!怎么是他?我满脑袋黑线，又陷入了深深的回忆中，他前世是我同门的师兄，我们奉命师命从崂山下来，在人间历练，四处斩妖除魔，作为战友的我们却相互猜忌，因为当年在山上，我们同时爱上镜云师姐，并且为了争夺师姐，我们在祠堂里大打出手，由于闹得太大，惊动了掌门，我们师傅为了保护我们，不想让我们受到惩罚，于是让我们下山历练。\r\n\r\n那时正是天宝年间，天下大乱，我们加入了镇压安禄山的战斗中，安禄山为了夺取帝位，让手下的镇妖师从地狱第八层召唤出了无数鬼物，其中最强的就是那只魍魉。\r\n\r\n每场大型战乱都会崛起一些厉害的魍魉，他们靠吸取人类的欲望提升自己，而求生欲是最强的欲望。\r\n\r\n原本那安胖子是个有贼心没贼胆的，但他被那只魍魉附身了，一路杀伐，最终杀进洛阳，我和师兄奋力抵抗，保护皇上撤离，可那个镇妖师发现了我们体内的巨大灵力，想将灵力据为己有，就布下天罗地网，师兄为了拖延时间，保护我逃走，一个人去挑战镇妖师，临走前只留下一句话“替我照顾镜云。”\r\n\r\n安史之乱最终平定了，镇妖师被御林军活捉，那只魍魉也被我一张大极镇魂符打入了血池地狱，师兄却永远回不来了，我本以为我再也不会见到师兄了，可在我百年后来到了地狱，被封为镇狱军裨将，突然发现，我的上司，伏波将军的副将就是师兄!\r\n\r\n这又是怎样的孽缘啊，来到了人间怎么还能碰见他?不管了，毕竟他曾经是我师兄，而且还把镜云师姐留给了我，我还是打个招呼把，要不太不礼貌了。\r\n\r\n“顾宇琛!”我大喊道。\r\n\r\n他和我擦肩而过，继续向前走，像没听到一样。这么高冷?我有点蒙，我这师兄难道还在“记仇”?就在我还在纳闷的时候，顾宇琛已经走远了，留下我一个人在风中凌乱……\r\n\r\n到了晚上我还在想着今天和顾宇琛偶遇的事，好比容易遇到个熟人，人家还不认我，我越想越气，怎么?来到人间就不认你这个师弟了?你以为你排行比我高就了不起啊?在崂山的时候你就仗着是我师兄事事都与我争!算了，这个师兄没有也罢。\r\n\r\n“叮”，在我还在怄气的时候，手机屏幕亮了起来，“我是狂躁吉他社的杨宇学长，学弟有兴趣加入吗?”我正在狂躁中无法自拔，你还想让我更狂躁吗?\r\n\r\n我刚要摔出去，手机又亮了，“小泽，我是你师兄，我来这里是来找qtgg的，今天的事你别生气，我是为了隐藏身份，手机里说不方便，等一下次见了面再和你说。”\r\n\r\nqtgg，难道是?青铜鬼棺!真的是师兄发来的，伯奇那老妖精还没死?想到这儿我后脖颈一阵发麻，这场天地间的浩劫怕是躲不过了。\r\n\r\n过了一会儿，一只花狸猫突然跳到窗上，用爪子轻轻抓着窗框，我战战兢兢的走过去，走近一看，惊奇的发现，猫嘴里叼着一片信笺，它是来送信的。\r\n\r\n没错，就是顾师兄的御灵术，是他操控的这只猫，我正开猫嘴拿出信笺，将信纸打开一看，上面是工整的颜体楷书:“小泽，我是顾宇琛，我奉天道之命来到人间，化名成了杨宇，寻找丢失的鬼棺，明天酉时我们三食堂二楼见面，具体我们见面时说，还有，别暴露身份，小心刺客。”\r\n\r\n我强忍住激动的泪水，将信烧掉，师兄你放心，有我们在，他就算再来几个鬼王，在人间也掀不起大浪。', 1, '2021-04-10', 1);
INSERT INTO `note` VALUES (5, '青铜鬼棺（3）', '第三章 小心楼上的鬼\n\n第二天，我早早准备妥当，和师兄约定的酉时还未到，我就已经赶到了三食堂二楼，顾师兄到的比我还早，我一溜小跑蹿了过去，可是当我走近时，隐约感觉有些不对，我放出神识，突然发现，师兄没有心跳，我的心咯噔一下，他竟然!已经死了。\n\n我不能接受这事实，我来到师兄面前，师兄淡淡一笑，对我说:“小泽，很抱歉，刚刚重逢我就又要离开你了，我在美院里隐藏这么久，就是为了杀掉楼上那畜生。” 我打断他:“什么?楼上有鬼?”说到这，我感到后背一凉。\n\n师兄继续说道:“可没想到，她太强了，我用我毕生修为将她禁锢在这里，我只能做这些了，小泽，你是我们崂山最优秀的弟子，斩妖除魔是崂山弟子的天职，我走了之后，你要帮人间除掉这个祸害。” 这时，他的声音颤抖了起来 “小泽，我就要走了，但我还有件事一直没和你说，你的身世原本……”\n\n顾师兄的话还未说完，就化作了一缕轻烟，他用尽了最后一股精神力化作分身，就只为和我见最后一面，“师兄，你别走!”我伸出手想把他拉住，但他越飘越高，最终消失在空中。\n\n我呆呆的望着空中，这一切来的快去的也快，曾经的爱恨情仇一幕幕浮现在我眼前，那段往事是多么让人留恋，可我还没来得及和师兄好好叙旧，师兄就这么走了……\n\n带着失去亲人般的痛苦走出食堂，我抬头望向三楼，那里看起来一切正常，人头攒动，窗口不断传出歌声，最近“校园好声音”复赛正在里面风风火火的举办，没有师兄说的那鬼物，可当我睁开阴阳眼，一切真相大白，哪里有什么人影，这都是那鬼物的障眼法，窗口挂着的是一排尸体，人们看到的那些人影，都是尸体的怨气所化。\n\n我再仔细一看，那尸体里面还有一个熟悉的面孔，他是……我的师兄，泪水一瞬间噙双眼，师兄，你等着，我一定杀了这畜生，我要为你报仇!\n\n接下来几天，我都闷在寝室里画符，对付那鬼物一定要用高级符才能镇压，能制造鬼空间的，一般都是慑青鬼的实力。在地狱中，鬼物都是分等级的，最弱的是孤魂野鬼，一般是那些死不瞑目的人，凝聚的怨气所化，鬼的怨气约重，就越强，等级依次是怨鬼、厉鬼、慑青鬼、鬼将、鬼王。\n\n若是慑青鬼出世，在这世上便是一场浩劫，若不及时镇压，整座城的生命都将不复存在，还好师兄将她及时禁锢，否则后果不堪设想，如今师兄已死，剩下的就交给我吧。\n\n记得我当年做镇狱军教头的时候，曾在冰山地狱叱咤风云，斩杀了无数作恶多端的鬼物，连鬼王都敬我三分，这种慑青鬼在我面前，不过只需弹弹手指，她就会灰飞烟灭，可如今的我只是肉身凡胎，实力大不如前，连实力强悍的师兄都被杀死了，这只鬼的实力不容小觑，但无论多凶险我也要一试，杀我师兄者，虽远必诛。\n\n我的目光更加坚毅，画符的速度也在加快，还剩最后几张符了，我用刀划破左手无名指，将血滴在符上，镇邪祟符泛起一道浅浅的金光，瞬间从中品提升到了极品等级。\n\n当年在崂山修炼时，记得师傅曾说，无名指与心脏相连，凝聚着修道之人的精血，不到关键时候不要乱用，会折损阳寿，为了给师兄报仇，拼了!\n\n这几天学校失踪的人越来越多了，校方也发现了食堂三楼的问题，但为了“迎评”工作的顺利进行，一直在压着这件事，聘请了几个“大师”来驱鬼，可是那些人都是江湖骗子，没什么真本事，甚至有的都从没见过真的鬼，糊弄一圈就拿钱走人，谁还管你会不会再死人。\n\n“大师”走后，人还在不断的失踪，最后校方不得不将食堂封起来，也许是楼下的商家利欲熏心，每天嚷着要校方付赔偿金，为了不减少学校建职工宿舍的预算，校方不得不开放食堂一二楼。\n\n虽然师兄在世时，已经将那鬼物封印在了三楼，楼下目前还是很安全，但后天就是月圆之夜，阴气最盛的时候，那鬼物一定会突破封印，营造出更大的鬼空间，到时候别说食堂大楼，就连整个学校都可能被吞噬。\n\n经过几天的观察，我发现这鬼物营造的鬼空间和当年老虎岭战役中遇到的有几分相似，没准这鬼物是伯奇鬼王的部下，天赐的良机，此次若抓住这鬼物，没准能逼问出青铜鬼棺的下落。可面对这杀了我师兄的强大的鬼物，想一箭双雕却谈何容易。\n\n我必须抓紧时间准备，明天是灭她的最后期限，我纵使付出生命的代价也要除掉她，敢在我镇狱将军司少泽的地盘为非作歹，一定让你有来无回。', 1, '2021-04-11', 1);
INSERT INTO `note` VALUES (7, '我的新笔记', '这是我的第一个在系统里建立的笔记', 0, '2021-04-11', 1);
INSERT INTO `note` VALUES (8, '我要进工作室', 'insert into RDC (member) values (me);', 1, '2021-04-15', 1);
INSERT INTO `note` VALUES (9, '老张的第一个笔记', '这是老张用户的第一个笔记，纪念一波', 1, '2021-04-14', 2);
INSERT INTO `note` VALUES (10, 'javafx笔记', ' JavaFX 常用类\n（一）基础\nTextField\nPasswordField\nLabel\nText （放置文本的类，需要设置宽度达到自动换行）\n//让文本自动换行**\nAnchorPane.setLeftAnchor(flow, 0.0);\nAnchorPane.setRightAnchor(flow, 0.0);\nHyperlink 放置超链接\n//借助HostServices实现打开默认浏览器\nHostServices hostServices = getHostServices();\nhostServices.showDocument(hyperlink.getText());\n\n（二）菜单栏\nMenuBar\nMenu\nMenuItem\nSeparatorMenuItem 分割线\nToggleGroup 制定单选组\nRadioMenuItem 单选\nCheckMenuItem 多选\nCustomMenuItem 用户自定义，通过setContent方法添加任意布局（组件）\n\n其他菜单项\nMenuButton 下拉列表，在下面可以添加MenuItem\nSplitMenuButton 同MenuButton（样式不一样）\nContextMenu 指定右键菜单（要给需要右键的元素加setMenuButton，也可以单击时通过show调用）\n\nChoiceBox 下拉列表\nComboBox 下拉列表，允许编辑setEditable,设置提示文字setPromptText,setPlaceholder设置占位符（一般是无数据的提示）\ncomboBox和choiceBox传入值是对象时，修改对象里的姓名下拉列表不更新的问题，comboBox可以清除选择，再选择，choicBox只能移除对象再插入到原来的位置\ncomboBox可以通过setCellFactory自定义下拉框样式，通过继承ListCell再重写updateItem方法\nColorPicker颜色选择器\nDatePicker日期选择器\nPagination分页控件\nSlider进度条组件可拖动，ProgressBar、ProgressIndicator不可拖动\nSpinner一个数字输入框，也可以放字符串可观察列表，也可以放对象，再通过工厂方法修改显示内容\nScrollBar滚动条，通过valueProperty进行监听\nSeparator分隔线\nListView显示列表（可以设置编辑，编辑时可以是下拉列表选择）\n\n（三）面板\nTitledPane 带标题的可折叠组件,Accordion 用来管理TitledPane\nTabPane,Tab选项卡组件\nSplitPane设置可拖动大小面板，通过setDividerPosition设置每个区域所占宽或高度\nScrollPane滚动面板\n————————————————\n版权声明：本文为CSDN博主「dong147258369」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。\n原文链接：https://blog.csdn.net/dong147258369/article/details/109227979', 0, '2021-04-14', 3);
INSERT INTO `note` VALUES (11, 'javafx笔记1', 'JavaFX 平台取代了 Swing 和 AWT\n主要用于开发富因特网应用\nJavaFX 可以无缝地在桌面或者WEB浏览器中运行\nJavaFX 为支持触摸的设备提供多点触控支持\nJavaFX 具有内建的 2D、3D 动画支持，以及视频和音频的回放功能，可以作为一个应用独立运行或者在浏览器中运行\n————————————————\n版权声明：本文为CSDN博主「迟遇_」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。\n原文链接：https://blog.csdn.net/weixin_47882161/article/details/111909809', 1, '2021-04-14', 3);
INSERT INTO `note` VALUES (12, 'java日期与字符串转换', '日期时间转字符串形式\n通过 SimpleDateFormat\n如果日期时间是 java.util.Date 类型，步骤如下：\n\n创建指定字符串格式形式的 java.text.SimpleDateFormat 类。\n调用 java.text.SimpleDateFormat 类的 format 方法，将指定的时间实例（java.util.Date 类实例）传入方法。\n示例：\n\nimport java.text.SimpleDateFormat;\nimport java.util.Date;\n\npublic class Demo {\n\n    public static void main(String[] args) {\n        SimpleDateFormat sdf = new SimpleDateFormat(\"yyyy-MM-dd HH:mm:ss\");\n        Date date = new Date();\n        String dateStr = sdf.format(date);\n        System.out.println(dateStr);\n    }\n}\n通过 joda-time 库\n利用第三方日期时间库 joda-time，步骤如下：\n\njoda-time 可将 java.util.Date 或 java.util.Calendar 对象转换为 joda-time 的 org.joda.time.DateTime 类对象。\n调用 org.joda.time.DateTime 类的 toString 方法，toString 方法支持日期时间格式转化（pattern）。\n示例：\n\nimport org.joda.time.DateTime;\n\nimport java.util.Calendar;\nimport java.util.Date;\nimport java.util.Locale;\n\npublic class Demo {\n\n    public static void main(String[] args) {\n        Date date = new Date();\n        DateTime dateTime = new DateTime(date);\n\n        System.out.println(dateTime.toString(\"yyyy-MM-dd HH:mm:ss\"));\n        System.out.println(dateTime.toString(\"yyyy年MM月dd日 HH:mm:ss EE\", Locale.CHINESE));\n\n        Calendar calendar = Calendar.getInstance();\n        DateTime dateTime1 = new DateTime(calendar);\n\n        System.out.println(dateTime1.toString(\"yyyy/MM/dd HH:mm:ss,SSS\"));\n        System.out.println(dateTime1.toString(\"yyyy-MM-dd hh:mm:ss a EE\", Locale.US));\n    }\n}\n字符串转日期时间类型\n通过 SimpleDateFormat\n步骤如下：\n\n创建指定字符串格式形式的 java.text.SimpleDateFormat 类。\n调用 java.text.SimpleDateFormat 类的 parse 方法。\n示例：\nimport java.text.ParseException;\nimport java.text.SimpleDateFormat;\nimport java.util.Date;\n\npublic class Demo {\n\n    public static void main(String[] args) throws ParseException {\n\n        SimpleDateFormat sdf = new SimpleDateFormat(\"yyyy-MM-dd HH:mm:ss\");\n        Date date = sdf.parse(\"2019-07-28 22:39:13\");\n        System.out.println(date);\n        //  转时间戳\n        System.out.println(date.getTime());\n    }\n}', 1, '2021-04-14', 3);
INSERT INTO `note` VALUES (13, '酋长国王——亨利', '当时光的列车缓缓驶过酋长球场，32岁的亨利就在那里，深情的目光望过去都是自己22岁的影子，还是那辆列车随着时光送走了匆匆过客。静静开往另一片大陆，33岁的亨利就在那里，深情的目光望去依稀浮现自己25岁的模样，远方的期许固然美好，而列车的短暂停留更好像岁月的美丽回眸。\n\n当时光奏出回家的天籁，35岁的亨利就在那里，深情的目光望去勾勒出自己29岁的动人画面，渐行渐远的车辙默默带走了属于四座城市的喧嚣，却指引着一路跟随的人们去追寻着那段逝去的时光。\n\n当岁月含泪悄悄转身，37岁的亨利就在那里，深情的目光望过去试图回到原点，那个出发的站台记起自己背起行囊时，那十七岁的样子。\n\n就在那时光隧道里总有一个瞬间让你分不清自己是32岁还是22岁，总有一次相遇让你无悔倾尽所有过往，总有一幕场景让你以为青春可以重来，总有一次回首让你怎么也看不清自己年轻的模样。走出时光隧道你终于豁然开朗，你感激它给了你5段精彩纷呈的旅程，给了你一生无法割舍的枪手情缘。\n\n远去的背影，还是回到伦敦吧，通往海布里的快车一趟一趟的运行著。这里面总会走过客，迎来新生。06年5月7日，即将送走的过客正是93岁的枪手圣地-海布里。队长亨利上演帽子戏法为这座拥有无限辉煌的球场告别。看台上的伊恩赖特激动万分，他是阿森纳的传奇。又被今天的传奇亨利超越。都是在这片草坪上，那里面有太多的思念太多的故事。融汇在这座93年的足球圣殿，融汇在国王亨利深情的一吻中。\n\n当烟花升起的时刻，那个曾属于亨利的海布里国王时代不会随年华逝去，而只会在年华的飘零中常常记起。', 1, '2021-04-15', 8);
INSERT INTO `note` VALUES (14, 'K神无双——克洛泽', '危难的关头，克洛泽替补出场，第四次踏上了世界杯赛场，仅仅三分钟后K神亮剑，比分追平，接下来的一幕就算是兑现一段迟来的诺言，只见K式空翻重现江湖。这一个瞬间让人泪流满面，仿佛带我们回到了12年前、仿佛札幌球场青涩的少年，其实时光从未走远，尽管空翻落地已经显得有些踉跄，但是米洛斯拉夫克洛泽 ，那颗会飞的心让他从新找回了青春的自己——克洛泽', 1, '2021-04-15', 8);
INSERT INTO `note` VALUES (15, '只有一个罗纳尔多！', '岁月你别催，该来的我不推；岁月你别催，走远的仍要追。当不得不说再见的时候，挥别的那一刻就如同流水的光阴，谁能抵得过，谁能叹息、奈何。\n\n他是天才，但无奈天妒英才；他屡屡倒下，但他从未放弃；他有一个脆弱的膝盖，更有一颗坚强的心.他说自己不会轻易倒下，因为他是罗纳尔多。\n\n20年，人生能有几个20年，生活就像一把无情刻刀，改变了你的模样，改变了岁月，改变了江湖，改变了不朽，改变了悲伤，改变了往事，改变了时光，不曾改变的，只剩下球迷永远的呐喊：世上只有一个罗纳尔多！', 0, '2021-04-15', 8);
INSERT INTO `note` VALUES (16, '足球精灵——罗纳尔迪尼奥', '我还记得，那个露着龅牙、天真无邪的笑脸\n我还记得，那个舞动身姿、跳跃在绿茵舞场的顽童\n我还记得，那个奔跑着、扭跃着、大笑着的精灵\n\n千军万马间的挑传，凭栏妄四顾，无所畏惧\n百步穿杨侧的静默，四两拨千斤，了无张扬\n轻拢慢捻处的写意，无愧汗浸衫，无关忠心\n沙场诀别时的泪光，仗剑任疏狂，只剩动情\n\n这是真正的放浪，这是真正的随性，这是真正的诗人。无惧随波逐流之浩淼，难觅孤鸿托梦之闲鹤，从南美大陆到法兰西，从加泰罗尼亚到米兰城，只信仰自我的足球哲学，只沉醉自我的脚下艺术\n\n该生生世世，奈何兜兜转转。谁愿糊里糊涂，终究牵牵挂挂。\n吟游山湖，纵横四海，多年后那一缕飘逸的马尾，早已沉浸那阙凌乱的记忆，成却永恒的传奇，独奏行云流水间跨越颠峰的曲高和寡。\n他从来便无关胜败，他的快乐早已超越胜败。\n物欲横流的足坛，当“快乐”已成为职业球员的稀缺品，只有罗纳尔迪尼奥依然在为自己与观众奉献着这项运动最原教旨主义的荷尔蒙。他的每一个毛孔都在喷射着欲望，那种对快乐的欲望，对足球原始性的欲望，对天赋与灵感的欲望。\n永远停伫于高山流水，永远独步于寻花斩月，永远醉心于轻茶淡墨。那一夜的伯纳乌，他碾碎拉莫斯，俘虏八万皇马拥趸；那一夜的斯坦福桥，他舞动着桑巴，原地出膛洞穿蓝血人希望；那一夜的圣西罗，他过关斩将，护送巴萨重返巅峰；那一夜的诺坎普，他两记助攻，目送梅西帽弑皇马，王储当立。\n登峰造极后的敛鞘解甲，也许一个转身就再也不见了正脸，也许一个背影就从此定格了想念，但回首相望，足球依然在那里转动，他的曼妙身姿依旧在这里挥毫——变的是青衫与青丝，不变的是青春与故事。\n人总说岁月从未远去，青春尚未离别。怎奈何年华无助飘零，记忆随风凋谢。\n看，他还在那里笑着，他还在那里扭动着。', 1, '2021-04-15', 6);
INSERT INTO `note` VALUES (18, 'David Beckham', '他是宠儿，也是弃儿\n\n他被追逐，也被放逐\n\n他在失重中重获尊重，更在尊重中获得更多的尊重\n\n他将离开，也永远不会离开\n\n他叫大卫 贝克汉姆\n\n他是一个牵动世界的人，而这次，他是一个动人的球员。——《贝影》', 1, '2021-04-15', 1);
INSERT INTO `note` VALUES (19, 'Un Año--Sebastian Yatra', '作词 : Sebastian Obando Giraldo/Andrés Torres/Mauricio Rengifo/Jesús Navarro/Julio Ramirez Eguia/Gilberto Marín Espinoza\n\n作曲 : Sebastian Obando Giraldo/Andrés Torres/Mauricio Rengifo/Jesús Navarro/Julio Ramirez Eguia/Gilberto Marín Espinoza\n\nYo te conocí en primavera\n\nMe miraste tú de primera\n\nDe un verano eterno me enamoré enamoré\n\nY esa despedida en septiembre\n\nEn octubre sí que se siente\n\nNoviembre sin ti me dolió también\n\nLlegará diciembre sigues en mi mente\n\nFueron seis meses y por fin volveré a verte\n\nLlegará febrero y yo seré el primero\n\nEn darte flores y decirte que te quiero\n\nPuede que pase un año más de una vez\n\nSin que te pueda ver\n\nPero el amor es más fuerte más fuerte\n\nPuede que el tiempo nos aleje otra vez\n\nSin saber dónde estés\n\nPero el amor es más fuerte\n\nUoh-oh-oh oh-oh oh-oh\n\nTe esperaré porque el amor es más fuerte\n\nHmmmm\n\nYa le dije a mis amigo\'\n\nYo no necesito a nadie\n\nSólo tú estás en mi mente\n\nMil kilómetros se restan\n\nCuando dos almas se suman\n\nA los lejos puedo ver\n\nSólo pienso sólo pienso en ti\n\nSólo pienso sólo pienso en ti\n\nYa mis primos saben tu apellido\n\nQue por ti yo estoy perdido\n\nEspero que también te pase a ti\n\nLlegará diciembre sigues en mi mente\n\nFueron seis meses y por fin volveré a verte\n\nLlegará febrero y yo seré el primero\n\nEn darte flores y decirte que te quiero\n\nPuede que pase un año más de una vez\n\nSin que te pueda ver\n\nPero el amor es más fuerte más fuerte\n\nPuede que el tiempo nos aleje otra vez\n\nSin saber dónde estés\n\nPero el amor es más fuerte\n\nOh-oh-oh oh-oh oh-oh\n\nTe esperaré porque el amor es más fuerte más fuerte\n\nOh-oh-oh oh-oh oh-oh\n\nTe esperaré porque el amor es más fuerte más fuerte\n\nYo te conocí en primavera\n\nMe miraste tú de primera', 1, '2021-04-15', 9);
INSERT INTO `note` VALUES (20, 'Traicionera--Sebastian Yatra', '作词 : Mauricio Rengifo/Andres Torres/Sebastián Obando\n\n作曲 : Mauricio Rengifo/Andres Torres/Sebastián Obando\n\nTu me dices que no es cierto que te mueres por mi\n你告诉我你爱慕我这不是真实的\nSi es verdad que no te gusto\n如果这是真的 你不爱我\nno te acerques asi\n不愿像爱人那样靠近我\nMe dijeron que te encanta que se mueran por ti\n他们告诉我你喜欢那些迷恋你的人\nBuscando al que se enamora\n期待一个坠入爱河的家伙\npara hacerlo sufrir\n让他痛苦不堪\nSi me dices que me amas\n如果你告诉我你爱我\nNo te voy a creer No\n我不会去相信你\nTu me dices que me quieres\n你告诉我你爱我\nY no puedes ser fiel No\n但你不会对我全心全意\nMe dejaste manejando solo y triste mujer No\n女人 你抛下我离开 留下我独自伤心\nTe confieso si lo quieres saber\n我会告诉你一切 如果你想知道\nSi lo quieres saber\n如果你想知道\nTraicionera\n你这个狡猾的人\nNo me importa lo que tu me quieras\n我不在乎你想从我这得到什么\nMentirosa\n你这个骗子\nSolo quieres que de amor me muera\n你只想让我为爱而死\nTraicionera\n你这个狡猾的人\nEn mi vida fuiste pasajera\n在我的生命中你只是个过路人\nMentirosa\n你这个骗子\nNo me importa que de amor te mueras\n对我来说这并不重要 你是否渴求爱情\nOhhhh\nOhhhh\nOhhhh\nOhhhh\nMentirosa\n你这个骗子\nNo me importa que de amor te mueras\n对我来说这并不重要 你是否渴求爱情\nSigues bailando reggaeton ton ton\n你不停的跳着雷鬼舞 咚 咚\nY no te importa para nada lo que sienta el corazon solo te importa el pantalon lon lon\n你丝毫不在乎你内心的感受 随性所欲 你只在乎你穿的那条裤子\nY se te nota desde lejos tu mal fica intencion Y, mira, no es tan facil\n你那邪恶的意图数米之外就能轻易看透 看吧 你的意图并不简单\nEnamorarme, nunca fue tan facil\n坠入爱河对我来说从来都没有那么容易\n(Estar cerca de mi)\n当你慢慢靠近我\nno es facil\n这没有那么轻巧\nEs que la vida se volvi dificil (solo por ti)\n生活渐渐变得困顿了 只因为你\nSi me dices que me amas\n如果你告诉我你爱我\nno te voy a creer, No\n我不会去相信你\nTu me dices que me quieres y no puedes ser fiel, No\n你告诉我你爱我 但你不会对我全心全意\nMe dejaste manejando solo y triste mujer, No\n女人 你抛下我离开 留下我独自伤心\nTe confieso si lo quieres saber\n我会告诉你一切 如果你想知道\nSi lo quieres saber\n如果你想知道\nTraicionera\n你这个狡猾的人\nNo me importa lo que tu me quieras\n我不在乎你想从我这得到什么\nMentirosa\n你这个骗子\nSolo quieres que de amor me muera\n你只想让我为爱而死\nTraicionera\n你这个狡猾的人\nEn mi vida fuiste pasajera\n在我的生命中你只是个过路人\nMentirosa\n你这个骗子\nNo me importa que de amor te mueras\n对我来说这并不重要 你是否渴求爱情\nOhhhh\nOhhhh\nOhhhh\nOhhhh\nMentirosa\n你这个骗子\nNo me importa que de amor te mueras\n对我来说这并不重要 你是否渴求爱情\nTu me dices que no es cierto que te mueres por mi\n你告诉我你爱慕我这不是真实的\nSi es verdad que no te gusto\n如果这是真的 你不爱我\nno te acerques asi\n不愿像爱人那样靠近我\nTraicionera\n你这个狡猾的人\nNo me importa lo que tu me quieras\n我不在乎你想从我这得到什么\nMentirosa\n你这个骗子\nSolo quieres que de amor me muera\n你只想让我为爱而死\nTraicionera\n你这个狡猾的人\nEn mi vida fuiste pasajera\n在我的生命中你只是个过路人\nMentirosa\n你这个骗子\nNo me importa que de amor te mueras\n对我来说这并不重要 你是否渴求爱情\nOhhhh\nOhhhh\nOhhhh\nOhhhh\nMentirosa\n你这个骗子\nNo me importa que de amor te mueras\n对我来说这并不重要 你是否渴求爱情\nOhhhh\nOhhhh\nOhhhh\nOhhhh\nMentirosa\n你这个骗子\nNo me importa que de amor te mueras\n对我来说这并不重要 你是否渴求爱情\nNo me importa que de amor te mueras\n对我来说这并不重要 你是否渴求爱情', 0, '2021-04-15', 9);

SET FOREIGN_KEY_CHECKS = 1;
